// Powered by OnSpace.AI
// VoiceDub Pro – Multi-Language Configuration

export type LanguageCode =
  | 'en' | 'ur' | 'ar' | 'fa' | 'tr' | 'hi'
  | 'ru' | 'bn' | 'zh' | 'ps' | 'sd' | 'bal';

export interface LanguageConfig {
  code: LanguageCode;
  name: string;       // Native name
  englishName: string;
  flag: string;
  isRTL: boolean;
  dir: 'ltr' | 'rtl';
}

export const LANGUAGES: LanguageConfig[] = [
  { code: 'en',  name: 'English',    englishName: 'English',    flag: '🇬🇧', isRTL: false, dir: 'ltr' },
  { code: 'ur',  name: 'اردو',       englishName: 'Urdu',       flag: '🇵🇰', isRTL: true,  dir: 'rtl' },
  { code: 'ar',  name: 'العربية',    englishName: 'Arabic',     flag: '🇸🇦', isRTL: true,  dir: 'rtl' },
  { code: 'fa',  name: 'فارسی',      englishName: 'Persian',    flag: '🇮🇷', isRTL: true,  dir: 'rtl' },
  { code: 'tr',  name: 'Türkçe',     englishName: 'Turkish',    flag: '🇹🇷', isRTL: false, dir: 'ltr' },
  { code: 'hi',  name: 'हिन्दी',      englishName: 'Hindi',      flag: '🇮🇳', isRTL: false, dir: 'ltr' },
  { code: 'ru',  name: 'Русский',    englishName: 'Russian',    flag: '🇷🇺', isRTL: false, dir: 'ltr' },
  { code: 'bn',  name: 'বাংলা',       englishName: 'Bengali',    flag: '🇧🇩', isRTL: false, dir: 'ltr' },
  { code: 'zh',  name: '中文',        englishName: 'Chinese',    flag: '🇨🇳', isRTL: false, dir: 'ltr' },
  { code: 'ps',  name: 'پښتو',       englishName: 'Pashto',     flag: '🇦🇫', isRTL: true,  dir: 'rtl' },
  { code: 'sd',  name: 'سنڌي',       englishName: 'Sindhi',     flag: '🇵🇰', isRTL: true,  dir: 'rtl' },
  { code: 'bal', name: 'بلوچی',      englishName: 'Balochi',    flag: '🇵🇰', isRTL: true,  dir: 'rtl' },
];

export const DEFAULT_LANGUAGE: LanguageCode = 'en';

// Translations
export type TranslationKey =
  | 'app_name' | 'tagline' | 'studio' | 'library' | 'effects' | 'export_tab' | 'settings'
  | 'record' | 'stop' | 'play' | 'pause' | 'mute' | 'unmute'
  | 'upload_video' | 'select_language' | 'add_track' | 'delete_track'
  | 'export_video' | 'export_audio' | 'ultra_hd' | 'dolby_atmos' | 'hdr'
  | 'reverb' | 'eq' | 'pitch' | 'compress' | 'noise_gate' | 'vocal_enhance'
  | 'buffer' | 'volume' | 'bass' | 'treble' | 'spatial'
  | 'no_projects' | 'start_dubbing' | 'recent_projects' | 'quality'
  | 'concert_mode' | 'studio_mode' | 'cinema_mode'
  | 'apply' | 'reset' | 'save' | 'cancel' | 'confirm'
  | 'track' | 'master' | 'mix' | 'playback_speed'
  | 'language' | 'theme' | 'about' | 'help' | 'version'
  | 'recording_tip' | 'buffer_size' | 'latency' | 'sample_rate';

export type Translations = Record<TranslationKey, string>;

const T: Record<LanguageCode, Translations> = {
  en: {
    app_name: 'VoiceDub Pro',      tagline: 'Studio-Grade Voice Dubbing',
    studio: 'Studio',              library: 'Library',
    effects: 'Effects',            export_tab: 'Export',       settings: 'Settings',
    record: 'Record',              stop: 'Stop',
    play: 'Play',                  pause: 'Pause',
    mute: 'Mute',                  unmute: 'Unmute',
    upload_video: 'Upload Video',  select_language: 'Select Language',
    add_track: 'Add Track',        delete_track: 'Delete Track',
    export_video: 'Export Video',  export_audio: 'Export Audio',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',     hdr: 'HDR 10+',
    reverb: 'Reverb',             eq: 'Equalizer',               pitch: 'Pitch Shift',
    compress: 'Compressor',       noise_gate: 'Noise Gate',       vocal_enhance: 'Vocal Enhancer',
    buffer: 'Buffer',             volume: 'Volume',              bass: 'Bass',
    treble: 'Treble',             spatial: 'Spatial Audio',
    no_projects: 'No Projects Yet',  start_dubbing: 'Start Dubbing',
    recent_projects: 'Recent Projects', quality: 'Quality',
    concert_mode: 'Concert Mode',    studio_mode: 'Studio Mode',   cinema_mode: 'Cinema Mode',
    apply: 'Apply',               reset: 'Reset',
    save: 'Save',                 cancel: 'Cancel',              confirm: 'Confirm',
    track: 'Track',               master: 'Master',
    mix: 'Mix',                   playback_speed: 'Playback Speed',
    language: 'Language',         theme: 'Theme',
    about: 'About',               help: 'Help',                  version: 'Version',
    recording_tip: 'Tap to start recording your dub',
    buffer_size: 'Buffer Size',   latency: 'Latency',            sample_rate: 'Sample Rate',
  },
  ur: {
    app_name: 'وائس ڈب پرو',      tagline: 'اسٹوڈیو گریڈ وائس ڈبنگ',
    studio: 'اسٹوڈیو',            library: 'لائبریری',
    effects: 'ایفیکٹس',           export_tab: 'ایکسپورٹ',        settings: 'ترتیبات',
    record: 'ریکارڈ',             stop: 'روکیں',
    play: 'چلائیں',               pause: 'توقف',
    mute: 'خاموش',                unmute: 'آواز آن',
    upload_video: 'ویڈیو اپلوڈ',  select_language: 'زبان منتخب کریں',
    add_track: 'ٹریک شامل',       delete_track: 'ٹریک حذف',
    export_video: 'ویڈیو ایکسپورٹ', export_audio: 'آڈیو ایکسپورٹ',
    ultra_hd: 'الٹرا ایچ ڈی+',   dolby_atmos: 'ڈولبی ایٹموس',   hdr: 'ایچ ڈی آر 10+',
    reverb: 'ریورب',              eq: 'ایکولائزر',               pitch: 'پچ شفٹ',
    compress: 'کمپریسر',          noise_gate: 'شور گیٹ',          vocal_enhance: 'وکل انہانسر',
    buffer: 'بفر',                volume: 'والیوم',               bass: 'باس',
    treble: 'ٹریبل',              spatial: 'اسپیشل آڈیو',
    no_projects: 'کوئی پروجیکٹ نہیں', start_dubbing: 'ڈبنگ شروع',
    recent_projects: 'حالیہ پروجیکٹس', quality: 'معیار',
    concert_mode: 'کنسرٹ موڈ',   studio_mode: 'اسٹوڈیو موڈ',    cinema_mode: 'سنیما موڈ',
    apply: 'لاگو',                reset: 'ری سیٹ',
    save: 'محفوظ',                cancel: 'منسوخ',               confirm: 'تصدیق',
    track: 'ٹریک',                master: 'ماسٹر',
    mix: 'مکس',                   playback_speed: 'پلے بیک اسپیڈ',
    language: 'زبان',             theme: 'تھیم',
    about: 'بارے میں',            help: 'مدد',                   version: 'ورژن',
    recording_tip: 'ڈب ریکارڈ کرنے کے لیے ٹیپ کریں',
    buffer_size: 'بفر سائز',      latency: 'لیٹینسی',            sample_rate: 'سیمپل ریٹ',
  },
  ar: {
    app_name: 'VoiceDub Pro',     tagline: 'دبلجة صوتية بجودة الاستوديو',
    studio: 'الاستوديو',          library: 'المكتبة',
    effects: 'المؤثرات',          export_tab: 'تصدير',           settings: 'الإعدادات',
    record: 'تسجيل',              stop: 'إيقاف',
    play: 'تشغيل',                pause: 'إيقاف مؤقت',
    mute: 'كتم',                  unmute: 'إلغاء الكتم',
    upload_video: 'رفع فيديو',    select_language: 'اختر لغة',
    add_track: 'إضافة مسار',      delete_track: 'حذف المسار',
    export_video: 'تصدير الفيديو', export_audio: 'تصدير الصوت',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'صدى',                eq: 'المعادل',                 pitch: 'نبرة الصوت',
    compress: 'ضاغط',             noise_gate: 'بوابة الضوضاء',   vocal_enhance: 'تحسين الصوت',
    buffer: 'المخزن المؤقت',      volume: 'الصوت',               bass: 'الجهير',
    treble: 'الحاد',              spatial: 'الصوت المكاني',
    no_projects: 'لا توجد مشاريع', start_dubbing: 'ابدأ الدبلجة',
    recent_projects: 'المشاريع الأخيرة', quality: 'الجودة',
    concert_mode: 'وضع الحفلة',   studio_mode: 'وضع الاستوديو',  cinema_mode: 'وضع السينما',
    apply: 'تطبيق',               reset: 'إعادة تعيين',
    save: 'حفظ',                  cancel: 'إلغاء',               confirm: 'تأكيد',
    track: 'مسار',                master: 'الرئيسي',
    mix: 'مزج',                   playback_speed: 'سرعة التشغيل',
    language: 'اللغة',            theme: 'المظهر',
    about: 'حول',                 help: 'مساعدة',                version: 'الإصدار',
    recording_tip: 'اضغط لبدء التسجيل',
    buffer_size: 'حجم المخزن',    latency: 'زمن الاستجابة',      sample_rate: 'معدل العينة',
  },
  fa: {
    app_name: 'VoiceDub Pro',     tagline: 'دوبله صدای استودیو',
    studio: 'استودیو',            library: 'کتابخانه',
    effects: 'جلوه‌ها',           export_tab: 'خروجی',           settings: 'تنظیمات',
    record: 'ضبط',                stop: 'توقف',
    play: 'پخش',                  pause: 'مکث',
    mute: 'بی‌صدا',               unmute: 'روشن',
    upload_video: 'آپلود ویدیو',  select_language: 'انتخاب زبان',
    add_track: 'افزودن ترک',      delete_track: 'حذف ترک',
    export_video: 'خروجی ویدیو',  export_audio: 'خروجی صدا',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'اکو',                eq: 'اکولایزر',                pitch: 'زیر و بم',
    compress: 'کمپرسور',          noise_gate: 'حذف نویز',         vocal_enhance: 'تقویت صدا',
    buffer: 'بافر',               volume: 'صدا',                 bass: 'بم',
    treble: 'زیر',                spatial: 'صدای فضایی',
    no_projects: 'پروژه‌ای نیست', start_dubbing: 'شروع دوبله',
    recent_projects: 'پروژه‌های اخیر', quality: 'کیفیت',
    concert_mode: 'حالت کنسرت',   studio_mode: 'حالت استودیو',   cinema_mode: 'حالت سینما',
    apply: 'اعمال',               reset: 'بازنشانی',
    save: 'ذخیره',                cancel: 'لغو',                 confirm: 'تأیید',
    track: 'ترک',                 master: 'مستر',
    mix: 'میکس',                  playback_speed: 'سرعت پخش',
    language: 'زبان',             theme: 'قالب',
    about: 'درباره',              help: 'راهنما',                version: 'نسخه',
    recording_tip: 'برای ضبط ضربه بزنید',
    buffer_size: 'اندازه بافر',   latency: 'تأخیر',              sample_rate: 'نرخ نمونه',
  },
  tr: {
    app_name: 'VoiceDub Pro',     tagline: 'Stüdyo Kalitesinde Seslendirme',
    studio: 'Stüdyo',             library: 'Kütüphane',
    effects: 'Efektler',          export_tab: 'Dışa Aktar',       settings: 'Ayarlar',
    record: 'Kaydet',             stop: 'Durdur',
    play: 'Oynat',                pause: 'Duraklat',
    mute: 'Sessiz',               unmute: 'Sesi Aç',
    upload_video: 'Video Yükle',  select_language: 'Dil Seç',
    add_track: 'Parça Ekle',      delete_track: 'Parçayı Sil',
    export_video: 'Videoyu Dışa', export_audio: 'Sesi Dışa',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'Yankı',              eq: 'Ekolayzer',               pitch: 'Perde',
    compress: 'Kompresör',        noise_gate: 'Gürültü Kapısı',  vocal_enhance: 'Ses Geliştirici',
    buffer: 'Tampon',             volume: 'Ses',                 bass: 'Bas',
    treble: 'Tiz',                spatial: 'Uzamsal Ses',
    no_projects: 'Proje Yok',     start_dubbing: 'Seslendirmeye Başla',
    recent_projects: 'Son Projeler', quality: 'Kalite',
    concert_mode: 'Konser Modu',  studio_mode: 'Stüdyo Modu',    cinema_mode: 'Sinema Modu',
    apply: 'Uygula',              reset: 'Sıfırla',
    save: 'Kaydet',               cancel: 'İptal',               confirm: 'Onayla',
    track: 'Parça',               master: 'Ana',
    mix: 'Miks',                  playback_speed: 'Oynatma Hızı',
    language: 'Dil',              theme: 'Tema',
    about: 'Hakkında',            help: 'Yardım',                version: 'Sürüm',
    recording_tip: 'Kaydı başlatmak için dokunun',
    buffer_size: 'Tampon Boyutu', latency: 'Gecikme',             sample_rate: 'Örnekleme Hızı',
  },
  hi: {
    app_name: 'VoiceDub Pro',     tagline: 'स्टूडियो-ग्रेड वॉइस डबिंग',
    studio: 'स्टूडियो',          library: 'लाइब्रेरी',
    effects: 'इफेक्ट्स',         export_tab: 'एक्सपोर्ट',       settings: 'सेटिंग्स',
    record: 'रिकॉर्ड',           stop: 'रोकें',
    play: 'चलाएं',               pause: 'रुकें',
    mute: 'म्यूट',               unmute: 'अनम्यूट',
    upload_video: 'वीडियो अपलोड', select_language: 'भाषा चुनें',
    add_track: 'ट्रैक जोड़ें',    delete_track: 'ट्रैक हटाएं',
    export_video: 'वीडियो एक्सपोर्ट', export_audio: 'ऑडियो एक्सपोर्ट',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'रिवर्ब',             eq: 'इक्वलाइज़र',              pitch: 'पिच',
    compress: 'कम्प्रेसर',        noise_gate: 'नॉइज़ गेट',       vocal_enhance: 'वोकल एन्हांसर',
    buffer: 'बफर',               volume: 'वॉल्यूम',             bass: 'बास',
    treble: 'ट्रेबल',             spatial: 'स्पेशियल ऑडियो',
    no_projects: 'कोई प्रोजेक्ट नहीं', start_dubbing: 'डबिंग शुरू करें',
    recent_projects: 'हाल के प्रोजेक्ट', quality: 'गुणवत्ता',
    concert_mode: 'कॉन्सर्ट मोड', studio_mode: 'स्टूडियो मोड',  cinema_mode: 'सिनेमा मोड',
    apply: 'लागू करें',           reset: 'रीसेट',
    save: 'सेव करें',             cancel: 'रद्द',                confirm: 'पुष्टि',
    track: 'ट्रैक',               master: 'मास्टर',
    mix: 'मिक्स',                 playback_speed: 'प्लेबैक स्पीड',
    language: 'भाषा',             theme: 'थीम',
    about: 'बारे में',            help: 'सहायता',                version: 'वर्शन',
    recording_tip: 'रिकॉर्डिंग शुरू करने के लिए टैप करें',
    buffer_size: 'बफर साइज़',     latency: 'लेटेंसी',            sample_rate: 'सैंपल रेट',
  },
  ru: {
    app_name: 'VoiceDub Pro',     tagline: 'Студийный дубляж голоса',
    studio: 'Студия',             library: 'Библиотека',
    effects: 'Эффекты',           export_tab: 'Экспорт',          settings: 'Настройки',
    record: 'Запись',             stop: 'Стоп',
    play: 'Играть',               pause: 'Пауза',
    mute: 'Без звука',            unmute: 'Со звуком',
    upload_video: 'Загрузить',    select_language: 'Выбрать язык',
    add_track: 'Добавить дорожку', delete_track: 'Удалить дорожку',
    export_video: 'Экспорт видео', export_audio: 'Экспорт аудио',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'Реверберация',       eq: 'Эквалайзер',              pitch: 'Высота тона',
    compress: 'Компрессор',       noise_gate: 'Шумоподавление',   vocal_enhance: 'Улучшение вокала',
    buffer: 'Буфер',              volume: 'Громкость',            bass: 'Бас',
    treble: 'Высокие',            spatial: 'Пространственный звук',
    no_projects: 'Нет проектов',  start_dubbing: 'Начать дублирование',
    recent_projects: 'Недавние проекты', quality: 'Качество',
    concert_mode: 'Концертный',   studio_mode: 'Студийный',       cinema_mode: 'Кинотеатр',
    apply: 'Применить',           reset: 'Сбросить',
    save: 'Сохранить',            cancel: 'Отмена',               confirm: 'Подтвердить',
    track: 'Дорожка',             master: 'Мастер',
    mix: 'Микс',                  playback_speed: 'Скорость',
    language: 'Язык',             theme: 'Тема',
    about: 'О приложении',        help: 'Помощь',                 version: 'Версия',
    recording_tip: 'Нажмите для записи',
    buffer_size: 'Размер буфера', latency: 'Задержка',            sample_rate: 'Частота дискретизации',
  },
  bn: {
    app_name: 'VoiceDub Pro',     tagline: 'স্টুডিও-গ্রেড ভয়েস ডাবিং',
    studio: 'স্টুডিও',           library: 'লাইব্রেরি',
    effects: 'ইফেক্টস',          export_tab: 'এক্সপোর্ট',       settings: 'সেটিংস',
    record: 'রেকর্ড',            stop: 'থামান',
    play: 'চালান',               pause: 'বিরতি',
    mute: 'মিউট',                unmute: 'আনমিউট',
    upload_video: 'ভিডিও আপলোড', select_language: 'ভাষা নির্বাচন',
    add_track: 'ট্র্যাক যোগ',    delete_track: 'ট্র্যাক মুছুন',
    export_video: 'ভিডিও এক্সপোর্ট', export_audio: 'অডিও এক্সপোর্ট',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'রিভার্ব',            eq: 'ইকুয়ালাইজার',             pitch: 'পিচ',
    compress: 'কম্প্রেসর',        noise_gate: 'নয়েজ গেট',        vocal_enhance: 'ভোকাল এনহান্সার',
    buffer: 'বাফার',              volume: 'ভলিউম',               bass: 'বাস',
    treble: 'ট্রেবল',             spatial: 'স্পেশিয়াল অডিও',
    no_projects: 'কোন প্রকল্প নেই', start_dubbing: 'ডাবিং শুরু করুন',
    recent_projects: 'সাম্প্রতিক প্রকল্প', quality: 'গুণমান',
    concert_mode: 'কনসার্ট মোড', studio_mode: 'স্টুডিও মোড',    cinema_mode: 'সিনেমা মোড',
    apply: 'প্রয়োগ',             reset: 'রিসেট',
    save: 'সেভ',                  cancel: 'বাতিল',               confirm: 'নিশ্চিত',
    track: 'ট্র্যাক',             master: 'মাস্টার',
    mix: 'মিক্স',                 playback_speed: 'প্লেব্যাক গতি',
    language: 'ভাষা',             theme: 'থিম',
    about: 'সম্পর্কে',            help: 'সাহায্য',               version: 'ভার্সন',
    recording_tip: 'রেকর্ড শুরু করতে ট্যাপ করুন',
    buffer_size: 'বাফার সাইজ',    latency: 'লেটেন্সি',           sample_rate: 'স্যাম্পল রেট',
  },
  zh: {
    app_name: 'VoiceDub Pro',     tagline: '专业级配音工作室',
    studio: '工作室',             library: '素材库',
    effects: '效果',              export_tab: '导出',             settings: '设置',
    record: '录音',               stop: '停止',
    play: '播放',                 pause: '暂停',
    mute: '静音',                 unmute: '取消静音',
    upload_video: '上传视频',     select_language: '选择语言',
    add_track: '添加轨道',         delete_track: '删除轨道',
    export_video: '导出视频',      export_audio: '导出音频',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: '混响',               eq: '均衡器',                  pitch: '音调',
    compress: '压缩器',           noise_gate: '噪声门',           vocal_enhance: '人声增强',
    buffer: '缓冲',               volume: '音量',                bass: '低音',
    treble: '高音',               spatial: '空间音频',
    no_projects: '暂无项目',       start_dubbing: '开始配音',
    recent_projects: '最近项目',   quality: '质量',
    concert_mode: '演唱会模式',   studio_mode: '工作室模式',      cinema_mode: '影院模式',
    apply: '应用',                reset: '重置',
    save: '保存',                 cancel: '取消',                confirm: '确认',
    track: '轨道',                master: '主控',
    mix: '混音',                  playback_speed: '播放速度',
    language: '语言',             theme: '主题',
    about: '关于',                help: '帮助',                  version: '版本',
    recording_tip: '点击开始录制您的配音',
    buffer_size: '缓冲大小',       latency: '延迟',               sample_rate: '采样率',
  },
  ps: {
    app_name: 'VoiceDub Pro',     tagline: 'د اسټوډیو کیفیت غږ ډبنګ',
    studio: 'اسټوډیو',           library: 'کتابتون',
    effects: 'اغیزې',             export_tab: 'صادرول',          settings: 'ترتیبات',
    record: 'ریکارډ',             stop: 'ودریږئ',
    play: 'چلوئ',                pause: 'ودریږئ',
    mute: 'غلی',                  unmute: 'غږ آن',
    upload_video: 'ویډیو آپلوډ',  select_language: 'ژبه وټاکئ',
    add_track: 'ټریک اضافه',      delete_track: 'ټریک حذف',
    export_video: 'ویډیو صادر',   export_audio: 'غږ صادر',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'ریورب',              eq: 'ایکولایزر',               pitch: 'پچ',
    compress: 'کمپریسر',          noise_gate: 'شور ګیټ',          vocal_enhance: 'غږ ښه کول',
    buffer: 'بفر',                volume: 'غږ',                  bass: 'باس',
    treble: 'ټریبل',              spatial: 'فضایي غږ',
    no_projects: 'پروژه نشته',    start_dubbing: 'ډبنګ پیل کړئ',
    recent_projects: 'وروستۍ پروژې', quality: 'کیفیت',
    concert_mode: 'کنسرټ موډ',   studio_mode: 'اسټوډیو موډ',    cinema_mode: 'سینما موډ',
    apply: 'پلي کول',             reset: 'بیا تنظیم',
    save: 'خوندي',                cancel: 'لغوه',                confirm: 'تایید',
    track: 'ټریک',                master: 'ماسټر',
    mix: 'مکس',                   playback_speed: 'چلولو سرعت',
    language: 'ژبه',              theme: 'تیم',
    about: 'د اړه',              help: 'مرسته',                 version: 'نسخه',
    recording_tip: 'د ریکارډ پیل لپاره ټاپ وکړئ',
    buffer_size: 'بفر اندازه',    latency: 'ځنډ',                sample_rate: 'سیمپل ریټ',
  },
  sd: {
    app_name: 'VoiceDub Pro',     tagline: 'اسٽوڊيو گريڊ وائس ڊبنگ',
    studio: 'اسٽوڊيو',           library: 'لائبريري',
    effects: 'اثر',              export_tab: 'ايڪسپورٽ',        settings: 'سيٽنگس',
    record: 'رڪارڊ',             stop: 'بند ڪريو',
    play: 'هلايو',               pause: 'روڪيو',
    mute: 'خاموش',               unmute: 'آواز آن',
    upload_video: 'ويڊيو اپلوڊ', select_language: 'ٻولي چونڊيو',
    add_track: 'ٽريڪ شامل',      delete_track: 'ٽريڪ ختم',
    export_video: 'ويڊيو ايڪسپورٽ', export_audio: 'آڊيو ايڪسپورٽ',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'ريورب',              eq: 'ايڪوالائيزر',             pitch: 'پچ',
    compress: 'ڪمپريسر',          noise_gate: 'شور گيٽ',          vocal_enhance: 'وڪل اينهانسر',
    buffer: 'بفر',                volume: 'واليوم',               bass: 'باس',
    treble: 'ٽريبل',              spatial: 'اسپيشل آڊيو',
    no_projects: 'ڪو پروجيڪٽ ناهي', start_dubbing: 'ڊبنگ شروع',
    recent_projects: 'تازا پروجيڪٽس', quality: 'معيار',
    concert_mode: 'ڪنسرٽ موڊ',   studio_mode: 'اسٽوڊيو موڊ',    cinema_mode: 'سنيما موڊ',
    apply: 'لاڳو',               reset: 'ري سيٽ',
    save: 'محفوظ',                cancel: 'منسوخ',               confirm: 'تصديق',
    track: 'ٽريڪ',               master: 'ماسٽر',
    mix: 'مڪس',                  playback_speed: 'پليٽ بيڪ اسپيڊ',
    language: 'ٻولي',             theme: 'ٿيم',
    about: 'باري ۾',             help: 'مدد',                   version: 'ورزن',
    recording_tip: 'ڊب رڪارڊ ڪرڻ لاءِ ٽيپ ڪريو',
    buffer_size: 'بفر سائيز',     latency: 'ليٽنسي',             sample_rate: 'سيمپل ريٽ',
  },
  bal: {
    app_name: 'VoiceDub Pro',     tagline: 'اسٹوڈیو کیفیت آواز ڈبنگ',
    studio: 'اسٹوڈیو',           library: 'لائبریری',
    effects: 'اثرات',             export_tab: 'برآمد',           settings: 'ترتیبات',
    record: 'ضبط',               stop: 'بند',
    play: 'پلے',                 pause: 'توقف',
    mute: 'خاموش',               unmute: 'آواز',
    upload_video: 'ویڈیو آپلوڈ', select_language: 'زبان انتخاب',
    add_track: 'ٹریک اضافہ',     delete_track: 'ٹریک حذف',
    export_video: 'ویڈیو برآمد', export_audio: 'آڈیو برآمد',
    ultra_hd: 'Ultra HD+',        dolby_atmos: 'Dolby Atmos',    hdr: 'HDR 10+',
    reverb: 'ریورب',              eq: 'ایکولائزر',               pitch: 'پچ',
    compress: 'کمپریسر',          noise_gate: 'شور گیٹ',          vocal_enhance: 'وکل انہانسر',
    buffer: 'بفر',                volume: 'آواز',                bass: 'باس',
    treble: 'ٹریبل',              spatial: 'فضائی آواز',
    no_projects: 'کوئی پروجیکٹ نیست', start_dubbing: 'ڈبنگ شروع',
    recent_projects: 'اخیرین پروجیکٹ', quality: 'معیار',
    concert_mode: 'کنسرٹ موڈ',   studio_mode: 'اسٹوڈیو موڈ',    cinema_mode: 'سینما موڈ',
    apply: 'لاگو',                reset: 'ری سیٹ',
    save: 'ذخیره',                cancel: 'لغو',                 confirm: 'تأیید',
    track: 'ٹریک',                master: 'ماسٹر',
    mix: 'مکس',                   playback_speed: 'پلے بیک سرعت',
    language: 'زبان',             theme: 'تھیم',
    about: 'درباره',              help: 'مدد',                   version: 'نسخه',
    recording_tip: 'ضبط شروع کردن برای ضربه بزن',
    buffer_size: 'بفر اندازه',    latency: 'تأخیر',              sample_rate: 'سیمپل ریٹ',
  },
};

export function getTranslations(lang: LanguageCode): Translations {
  return T[lang] ?? T['en'];
}

export function getLanguageConfig(code: LanguageCode): LanguageConfig {
  return LANGUAGES.find(l => l.code === code) ?? LANGUAGES[0];
}
